kind: ConfigMap 
apiVersion: v1 
metadata:
  name: generic-configmap 
data:
  # Configuration values can be set as key-value properties
  mysql_host: db.cscs.ch
  mysql_username: root
  env_var1: "Variable 1 from env"
  env_var2: "Variable 2 from env"
  
  # Or set as complete file contents (even JSON!)
  keys: | 
    env_var1="Variable 1 from env"
    env_var2="Variable 2 from env"
